### ISSUE TITLE
Regarding Documentation and Readme 

### ISSUE THREAD

**Issue by suki1504** [NavinKumarMNK/Anomaly-Crime-Activity-Detection#2]
Hai @NavinKumarMNK 

Thanks for uploading code and its very useful.

How to run this code without docker. can you please share documentation file local installation

thanks

**Comment by cosmic-heart** [comment]
You can just run the app.py
Docker is only for containerization and deployment.
BTW the models are still not yet trained. pre-training these models need high compute resource.  
This project is not yet documented.

**Comment by suki1504** [comment]
@NavinKumarMNK 

if you dont mind can you please share pre-trained model ,dataset and other resources 

Thanks

**Comment by cosmic-heart** [comment]
As I said, model is not yet trained. It is still in the development
Dataset : https://www.kaggle.com/datasets/webadvisor/real-time-anomaly-detection-in-cctv-surveillance
I didn't refer to any resources. I would suggest you to work with finished & published methodologies.
Even my methodology have some problems which will take some time to solve it!
